Repository teamGreenGreen/CookieRunAPIServer, pull requests merged in 2024-02, with the labels that each got.

#13 GameDB connection, Edit GameResultController
  Controllers/DTO/GameResult.cs
  Controllers/GameResultController.cs
  DBConfig.cs
  Program.cs
  Repository/GameDB.cs
  Repository/GameDB_Result.cs
  appsettings.Development.json
Labels: Server

#23 인증서버 회원가입 기능 구현
  API_Game_server/Controllers/DTO/Account.cs
  Auth_Server/Controllers/AccountController.cs
  Auth_Server/DAO/Account.cs
  Auth_Server/DAO/AccountDB.cs
  Auth_Server/DTO/CreateAccount.cs
  Auth_Server/DTO/LoginAccount.cs
  Auth_Server/ErrorCode.cs
  Auth_Server/Repository/AccountDB.cs
Labels: enhancement

#25 코드 정리, 경로 수정
  API_Game_server/Controllers/AccountController.cs
  API_Game_server/Controllers/RankController.cs
  API_Game_server/Model/DTO/Account.cs
  API_Game_server/Model/DTO/GameResult.cs
  API_Game_server/Model/DTO/Rank.cs
  API_Game_server/Program.cs
  Auth_Server/Controllers/AccountController.cs
  Auth_Server/Model/DAO/Account.cs
  Auth_Server/Model/DTO/CreateAccount.cs
  Auth_Server/Model/DTO/LoginAccount.cs
  Auth_Server/Program.cs
  Auth_Server/Repository/AccountDB.cs
Labels: refactor

#30 #29 로그인 기능 구현
  Auth_Server/Controllers/AccountController.cs
  Auth_Server/ErrorCode.cs
  Auth_Server/Model/DTO/LoginAccount.cs
  Auth_Server/Repository/AccountDB.cs
Labels: enhancement

#33 structureChange#32
  API_Game_server/Controllers/FriendRequestController.cs
  API_Game_server/ErrorCode.cs
  API_Game_server/Model/DAO/FriendRequest_DAO.cs
  API_Game_server/Model/DTO/ErrorCode_DTO.cs
  API_Game_server/Model/DTO/FriendRequest_DTO.cs
  API_Game_server/Program.cs
  API_Game_server/Services/FriendRequestService.cs
  API_Game_server/Services/ValidationService.cs
Labels: Server

#34 친구 요청 기능 구현 완료
  API_Game_server/Model/DAO/FriendRequest_DAO.cs
  API_Game_server/Repository/GameDB_FriendRequest.cs
  API_Game_server/Repository/RedisDB_Set.cs
  API_Game_server/Services/FriendRequestService.cs
Labels: Server

#38 Game result
  API_Game_server/Controllers/GameResultController.cs
  API_Game_server/Controllers/RankController.cs
  API_Game_server/ErrorCode.cs
  API_Game_server/Model/CookieData.cs
  API_Game_server/Model/DAO/GameResult_DAO.cs
  API_Game_server/Model/DTO/GameResult_DTO.cs
  API_Game_server/Model/ItemData.cs
  API_Game_server/Model/UserLevelData.cs
  API_Game_server/Program.cs
  API_Game_server/Repository/GameDB_Result.cs
  API_Game_server/Resources/CookieData.csv
  API_Game_server/Services/GameResultService.cs
  API_Game_server/Services/ValidationService.cs
Labels: Server

#40 #39 구조 변경
  Auth_Server/Controllers/AccountController.cs
  Auth_Server/Program.cs
  Auth_Server/Repository/AccountDB.cs
  Auth_Server/Services/AuthService.cs
Labels: refactor

#46 duplicationError Fix
  API_Game_server/Model/DTO/Friend/FriendRequestList_DTO.cs
  API_Game_server/Services/FriendRequestAcceptService.cs
  API_Game_server/Services/FriendRequestService.cs
Labels: bug

#47 인증서버 구현 완료
  API_Game_server/Controllers/LoginController.cs
  API_Game_server/ErrorCode.cs
  API_Game_server/Model/DTO/Account_DTO.cs
  API_Game_server/Model/DTO/Login_DTO.cs
  API_Game_server/Program.cs
  API_Game_server/Repository/AccountDB.cs
  API_Game_server/Services/AuthService.cs
  Auth_Server/Controllers/AccountController.cs
  Auth_Server/Controllers/VerifyTokenController.cs
  Auth_Server/ErrorCode.cs
  Auth_Server/Model/DTO/VerifyToken_DTO.cs
  Auth_Server/Repository/AccountDB.cs
  Auth_Server/Services/AuthService.cs
Labels: enhancement

#49 Friend req list#45
  API_Game_server/Controllers/Friend/FriendRequestAcceptController.cs
  API_Game_server/Controllers/Friend/FriendRequestController.cs
  API_Game_server/Controllers/Friend/FriendRequestListController.cs
  API_Game_server/ErrorCode.cs
  API_Game_server/Model/DAO/Friend/FriendRequestList_DAO.cs
  API_Game_server/Model/DTO/Friend/FriendRequestList_DTO.cs
  API_Game_server/Program.cs
  API_Game_server/Repository/GameDB_FriendRequest.cs
  API_Game_server/Services/Friend/FriendRequestAcceptService.cs
  API_Game_server/Services/Friend/FriendRequestListService.cs
  API_Game_server/Services/Friend/FriendRequestService.cs
Labels: Server

#53 친구 목록 조회 기능 구현 완료
  API_Game_server/Controllers/Friend/FriendListController.cs
  API_Game_server/ErrorCode.cs
  API_Game_server/Model/DAO/Friend/FriendList_DAO.cs
  API_Game_server/Model/DTO/Friend/FriendList_DTO.cs
  API_Game_server/Program.cs
  API_Game_server/Services/Friend/FriendListServcie.cs
  API_Game_server/Services/Friend/FriendRequestService.cs
Labels: Server

#59 친구 삭제 기능 구현 완료
  API_Game_server/Controllers/Friend/FriendDeleteController.cs
  API_Game_server/Model/DAO/Friend/FriendDelete_DAO.cs
  API_Game_server/Model/DTO/Friend/FriendDelete_DTO.cs
  API_Game_server/Program.cs
  API_Game_server/Repository/GameDB_FriendRequest.cs
  API_Game_server/Services/Friend/FriendDeleteService.cs
Labels: Server

#61 게임 서버 로그인 기능 구현
  API_Game_server/Controllers/LoginController.cs
  API_Game_server/ErrorCode.cs
  API_Game_server/Model/DAO/UserInfo_DAO.cs
  API_Game_server/Model/DTO/Login_DTO.cs
  API_Game_server/Program.cs
  API_Game_server/Repository/GameDB_User.cs
  API_Game_server/Security.cs
  API_Game_server/Services/AuthService.cs
  API_Game_server/Services/GameService.cs
Labels: enhancement

#62 Edit code
  API_Game_server/Controllers/GameResult/GameResultController.cs
  API_Game_server/Controllers/Mail/MailAddController.cs
  API_Game_server/Controllers/Mail/MailListController.cs
  API_Game_server/Controllers/Mail/MailOpenController.cs
  API_Game_server/ErrorCode.cs
  API_Game_server/Model/DAO/GameResult/GameResult_DAO.cs
  API_Game_server/Model/DTO/GameResult/GameResult_DTO.cs
  API_Game_server/Model/DTO/Mail/Mail_DTO.cs
  API_Game_server/Repository/GameDB_Mail.cs
  API_Game_server/Repository/GameDB_Result.cs
  API_Game_server/Services/GameResult/GameResultService.cs
  API_Game_server/Services/Mail/MailService.cs
Labels: Server

#67 유저 데이터 불러오기 기능 구현
  API_Game_server/Controllers/LoginController.cs
  API_Game_server/Model/DAO/UserInfo_DAO.cs
  API_Game_server/Model/DTO/Login_DTO.cs
  API_Game_server/Program.cs
  API_Game_server/Repository/GameDB_User.cs
  API_Game_server/Services/AuthService.cs
  API_Game_server/Services/GameService.cs
  API_Game_server/Services/UserService.cs
  Auth_Server/Controllers/AccountController.cs
  Auth_Server/Controllers/VerifyTokenController.cs
  Auth_Server/Model/DAO/Account_DAO.cs
  Auth_Server/Model/DTO/CreateAccount_DTO.cs
  Auth_Server/Model/DTO/LoginAccount_DTO.cs
  Auth_Server/Model/DTO/VerifyToken_DTO.cs
  Auth_Server/Repository/AccountDB.cs
  Auth_Server/Services/AuthService.cs
Labels: enhancement

#68 변수명 변경
  API_Game_server/Controllers/LoginController.cs
Labels: bug

#69 GameResult에 Redis 적용, 사용하지 않는 ErrorCode 정리, MailDTO 필요에 따라 구분
  API_Game_server/Controllers/Mail/MailListController.cs
  API_Game_server/Controllers/Mail/MailOpenController.cs
  API_Game_server/ErrorCode.cs
  API_Game_server/Model/DTO/Mail/Mail_DTO.cs
  API_Game_server/Repository/GameDB_Result.cs
  API_Game_server/Services/AttendanceService.cs
  API_Game_server/Services/AuthService.cs
  API_Game_server/Services/GameResult/GameResultService.cs
  API_Game_server/Services/Mail/MailService.cs
Labels: Server

#72 인증 미들웨어 구현 완료
  API_Game_server/ErrorCode.cs
  API_Game_server/Middleware/VerifyUserAuth.cs
  API_Game_server/Model/DAO/AuthInfo.cs
  API_Game_server/Program.cs
  API_Game_server/Repository/RedisDB_Auth.cs
  API_Game_server/Services/AuthService.cs
Labels: enhancement

#73 회원 가입 시 보상 지급
  API_Game_server/Controllers/LoginController.cs
  API_Game_server/ErrorCode.cs
  API_Game_server/Services/GameService.cs
Labels: Server

#74 인증 관련 DTO에 유효성 검사 추가
  API_Game_server/Model/DTO/Login_DTO.cs
  Auth_Server/Model/DTO/CreateAccount_DTO.cs
  Auth_Server/Model/DTO/LoginAccount_DTO.cs
  Auth_Server/Model/DTO/VerifyToken_DTO.cs
Labels: bug

#76 di 인터페이스 누락된 부분 추가
  Auth_Server/Controllers/AccountController.cs
  Auth_Server/Controllers/VerifyTokenController.cs
  Auth_Server/Model/DTO/CreateAccount_DTO.cs
  Auth_Server/Model/DTO/LoginAccount_DTO.cs
Labels: bug

#77 DB 중복 데이터 삽입 시 예외 처리 추가
  Auth_Server/ErrorCode.cs
  Auth_Server/Services/AuthService.cs
Labels: bug

#79 인증서버 - 로그인 인증 관련 버그 수정
  Auth_Server/Repository/AccountDB.cs
  Auth_Server/Repository/IAccountDB.cs
  Auth_Server/Services/AuthService.cs
Labels: bug

#84 friendEdit
  API_Game_server/Controllers/Friend/FriendDeleteController.cs
  API_Game_server/Controllers/Friend/FriendListController.cs
  API_Game_server/Controllers/Friend/FriendRequestAcceptController.cs
  API_Game_server/Controllers/Friend/FriendRequestController.cs
  API_Game_server/Controllers/Friend/FriendRequestDenyController.cs
  API_Game_server/Controllers/Friend/FriendRequestListController.cs
  API_Game_server/Model/DTO/Friend/FriendDelete_DTO.cs
  API_Game_server/Model/DTO/Friend/FriendList_DTO.cs
  API_Game_server/Model/DTO/Friend/FriendRequestAccept_DTO.cs
  API_Game_server/Model/DTO/Friend/FriendRequestDeny_DTO.cs
  API_Game_server/Model/DTO/Friend/FriendRequestList_DTO.cs
  API_Game_server/Model/DTO/Friend/FriendRequest_DTO.cs
  API_Game_server/Program.cs
  API_Game_server/Services/Friend/FriendDeleteService.cs
  API_Game_server/Services/Friend/FriendListServcie.cs
  API_Game_server/Services/Friend/FriendRequestAcceptService.cs
  API_Game_server/Services/Friend/FriendRequestDenyService.cs
  API_Game_server/Services/Friend/FriendRequestListService.cs
  API_Game_server/Services/Friend/FriendRequestService.cs
  API_Game_server/Services/Interface/IFriendDeleteService.cs
  API_Game_server/Services/Interface/IFriendListService.cs
  API_Game_server/Services/Interface/IFriendRequestAcceptService.cs
  API_Game_server/Services/Interface/IFriendRequestDenyService.cs
  API_Game_server/Services/Interface/IFriendRequestListService.cs
  API_Game_server/Services/Interface/IFriendRequestService.cs
Labels: Server

#85 Http 메시지에 세션 ID를 포함해서 보내도록 변경
  API_Game_server/Controllers/LoginController.cs
  API_Game_server/Middleware/VerifyUserAuth.cs
  Auth_Server/Controllers/AccountController.cs
  Auth_Server/Services/AuthService.cs
Labels: enhancement

#89 Friend edit2
  API_Game_server/Controllers/Friend/FriendListController.cs
  API_Game_server/Controllers/Friend/FriendRequestListController.cs
  API_Game_server/Middleware/VerifyUserAuth.cs
  API_Game_server/Model/DAO/Friend/FriendDelete_DAO.cs
  API_Game_server/Model/DAO/Friend/FriendRequestDeny_DAO.cs
  API_Game_server/Model/DTO/Friend/FriendList_DTO.cs
  API_Game_server/Model/DTO/Friend/FriendRequestList_DTO.cs
Labels: Server

#92 SessionId로 Redis, DB에 접근하도록 수정, 사용하지 않는 DTO, RedisUserInfo 삭제
  API_Game_server/Controllers/GameResult/GameResultController.cs
  API_Game_server/Controllers/Mail/MailListController.cs
  API_Game_server/Controllers/Mail/MailOpenController.cs
  API_Game_server/ErrorCode.cs
  API_Game_server/Model/DAO/RedisUserInfo.cs
  API_Game_server/Model/DTO/GameResult/GameResult_DTO.cs
  API_Game_server/Model/DTO/Mail/Mail_DTO.cs
  API_Game_server/Resources/UserLevelData.csv
  API_Game_server/Services/GameResult/GameResultService.cs
  API_Game_server/Services/Interface/IGameResultService.cs
  API_Game_server/Services/Interface/IMailService.cs
  API_Game_server/Services/Mail/MailService.cs
Labels: Server

#94 로비 씬에서 플레이어 정보를 가져오기 위한 Post 함수 생성
  API_Game_server/Controllers/UserInfoLoadController.cs
  API_Game_server/ErrorCode.cs
  API_Game_server/Middleware/VerifyUserAuth.cs
  API_Game_server/Model/DTO/UserInfo_DTO.cs
  API_Game_server/Resources/CookieData.csv
  API_Game_server/Services/GameResult/GameResultService.cs
  API_Game_server/Services/Interface/IUserService.cs
  API_Game_server/Services/UserService.cs
Labels: Server

#101 nowCookie
  API_Game_server/Controllers/NowCookieController.cs
  API_Game_server/Middleware/VerifyUserAuth.cs
  API_Game_server/Model/DTO/NowCookie_DTO.cs
  API_Game_server/Program.cs
  API_Game_server/Services/Interface/INowCookieService.cs
  API_Game_server/Services/NowCookieService.cs
Labels: Server

#103 Now cookie#100
  API_Game_server/Controllers/NowCookieController.cs
  API_Game_server/Model/DTO/NowCookie_DTO.cs
  API_Game_server/Services/Interface/INowCookieService.cs
  API_Game_server/Services/NowCookieService.cs
Labels: Server

#107 미들웨어에서 세션 ID를 검증하는 코드 추가
  API_Game_server/Middleware/VerifyUserAuth.cs
  API_Game_server/Repository/Interface/IRedisDB.cs
  API_Game_server/Repository/RedisDB_Auth.cs
Labels: enhancement

#110 메일함 열었을 때 redis에 변경된 유저 정보 저장하여 LobbyScene의 UserInfo 변경되도록 수정
  API_Game_server/Resources/UserLevelData.csv
  API_Game_server/Services/Mail/MailService.cs
  API_Game_server/appsettings - 복사.json
Labels: Server

#112 메일 삭제 구현
  API_Game_server/Controllers/Mail/MailDeleteController.cs
  API_Game_server/Model/DTO/Mail/Mail_DTO.cs
  API_Game_server/Services/Interface/IMailService.cs
  API_Game_server/Services/Mail/MailService.cs
Labels: Server

#114 레벨, 경험치 계산 버그 수정
  API_Game_server/Controllers/GameResult/GameResultController.cs
  API_Game_server/Services/GameResult/GameResultService.cs
  API_Game_server/Services/Interface/IGameResultService.cs
Labels: bug

#115 보상 문구 변경
  API_Game_server/Services/GameResult/GameResultService.cs
Labels: Server

#117 Fix attendance api2
  API_Game_server/Repository/GameDB_Attendance.cs
  API_Game_server/Services/AttendanceService.cs
  API_Game_server/Services/Interface/IAttendanceService.cs
  API_Game_server/Services/RankService.cs
Labels: bug

#119 프로젝트 도커로 띄우는 작업 완료
  API_Game_server/.dockerignore
  API_Game_server/API_Game_Server.csproj
  API_Game_server/Config/Database/Init/account.sql
  API_Game_server/Config/Docker/docker-compose.yml
  API_Game_server/Dockerfile
  API_Game_server/Program.cs
  Auth_Server/Dockerfile
  Auth_Server/Program.cs
  Config/Database/Dockerfile
  Config/Database/dump.sql
  docker-compose.yml
Labels: enhancement
